### ISSUE TITLE
Yaml structure

### ISSUE THREAD

**Issue by mod** [rubykube/arke#18]
Implement the following yaml parsing:
```
strategy:
  type: 'copy'
  target:
    driver: rubykube
    name: John
    key:
    secret:
  sources:
    - driver: bitfinex
      name: Joe
      key:
      secret:
```
